name: Codex CI

on:
  push:
    paths:
      - "docs/agents.md"
      - "tools/agents_protocol.py"
      - "tools/run_omega_cycle.py"
      - "tools/validate_kernel.py"
      - "tests/claude_regressions.json"
      - ".github/workflows/codex-ci.yml"
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install pyyaml
      - name: Validate kernel, policy, artifacts
        run: python tools/validate_kernel.py
